apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: aks-istio-system
  labels:
    helm.sh/chart: kiali-server-1.76.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v1.76.0"
    app.kubernetes.io/version: "v1.76.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 20001
    targetPort: 20001
  - name: http-metrics
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
