apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emartdb.fullname" . }}-deployment
  labels:
    app: emartdb
  {{- include "emartdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: emartdb
    {{- include "emartdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: emartdb:v1
      {{- include "emartdb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: emart-secrets
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: emart-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.emartdb.image.repository }}:{{ .Values.deployment.emartdb.image.tag
          | default .Chart.AppVersion }}
        name: emartdb
        ports:
        - containerPort: 3306
        resources: {}
      nodeSelector: {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: emartdb
  namespace: emart-dev
spec:
  type: ClusterIP
  selector:
    app: emartdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
