apiVersion: v1
kind: Service
metadata:
  name: {{ include "emartdb.fullname" . }}-emartdb
  labels:
  {{- include "emartdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.emartdb.type }}
  selector:
    app: emartdb
  {{- include "emartdb.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.emartdb.ports | toYaml | nindent 2 }}