apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-access-rolebinding
  namespace: emart-dev
subjects:
- kind: Group
  name: "0fba5acf-7f65-4dab-8ec8-52a14c0940ce"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-access-role
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-access-role
  namespace: emart-dev
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

