apiVersion: v1
kind: Secret
metadata:
  name: emart-secrets
  namespace: emart-dev
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZW1hcnRkYnBhc3M=
  MYSQL_DATABASE: Ym9va3M=
  MONGO_INITDB_DATABASE: ZXBvYw==