apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}-api
  labels:
  {{- include "client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: api
  {{- include "client.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.api.ports | toYaml | nindent 2 }}