apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}-client
  labels:
  {{- include "client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.type }}
  selector:
    app: client
  {{- include "client.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.client.ports | toYaml | nindent 2 }}