apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
  namespace: vpro-dev
  labels:
    app: vproapp
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: sabirchoudhury001/vprofileapp
        ports:
        - name: vproapp-port
          containerPort: 8080
          hostPort: 8080
        #env:
        #- name: MYSQL_HOST
        resources:
          limits:
            memory: 512Mi
            cpu: "250m"
          requests:
            memory: 256Mi
            cpu: "150m"
        readinessProbe:
          httpGet:
            path: /index
            port: vproapp-port
          initialDelaySeconds: 15
          periodSeconds: 10
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup vprodb; do echo waiting for mysqldb; sleep 2; done"]
      


---
apiVersion: v1
kind: Service
metadata:
  name: vproapp
  namespace: vpro-dev
spec:
  type: LoadBalancer
  selector:
    app: vproapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
