# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: vpro-dev
spec:
  provider: azure
  secretObjects:
  - secretName: sql-secret
    type: Opaque
    data:
      - objectName: sqladminpass
        key: sqladminpass
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: ebf2c760-ddb8-4149-871d-96547b4cf747   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: akskvmafprod            # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:   
        - |
          objectName: sqladminpass
          objectType: secret
          objectVersion: ""
    tenantId: "d52c9ea1-7c21-47b1-82a3-33a74b1f74b8"                # The tenant ID of the key vault