apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vpro-pvc
    namespace: vpro-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi