apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb-deployment
  namespace: vpro-dev
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: aksprodacr.azurecr.io/vprofiledb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpro-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: accounts  
        volumeMounts:
        - name: vpro-db-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: vpro-db-pvc
        persistentVolumeClaim:
          claimName: azure-managed-disk-pvc
       
---
apiVersion: v1
kind: Service
metadata:
  name: vprodb
  namespace: vpro-dev
spec:
  type: ClusterIP
  selector:
    app: vprodb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
