apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vprodb-deployment
  namespace: vpro-dev
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        #image: sabirchoudhury001/vprofiledb
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpro-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: accounts  
        volumeMounts:
         - name: vpro-db-pvc
           mountPath: "/var/lib/mysql"
      volumes:
      - name: vpro-db-pvc
        persistentVolumeClaim:
          claimName: vpro-pvc
       
---
apiVersion: v1
kind: Service
metadata:
  name: vprodb
  namespace: vpro-dev
spec:
  clusterIP: None
  selector:
    app: vprodb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  