apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
  labels:
    app: {{ .Values.appname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.appname }}
