apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-emart-secrets
  labels:
  {{- include "secrets.labels" . | nindent 4 }}
data:
  MONGO_INITDB_DATABASE: {{ required "emartSecrets.mongoInitdbDatabase is required"
    .Values.emartSecrets.mongoInitdbDatabase | b64enc | quote }}
  MYSQL_DATABASE: {{ required "emartSecrets.mysqlDatabase is required" .Values.emartSecrets.mysqlDatabase
    | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "emartSecrets.mysqlRootPassword is required" .Values.emartSecrets.mysqlRootPassword
    | b64enc | quote }}
type: Opaque