api:
  ports:
    port: 5000
    protocol: TCP
    targetPort: 5000
  type: ClusterIP
deployment:
  api:
    image:
      repository: emartapp
      tag: v1
  nodeSelector:
    nodepool-type: user-app
  replicas: 1
kubernetesClusterDomain: cluster.local
